# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines
- main
- develop

# pool:
#   vmImage: ubuntu-latest

pool: 
  name: Self_Hosted_Agent_Pool

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: PublishBuildArtifacts@1
  inputs:
    TargetPath: '$(Build.Repository.LocalPath)'
    artifact: '$(Build.DefinitionName)'
    # publishLocation: 'pipeline'
    publishLocation: 'C:\Users\ajinth.christudas\buildartifacts\'

