CREATE TABLE IF NOT EXISTS ODS.PERSON 
(
    PERSON_ID INTEGER IDENTITY(1,1)
,    FIRST_NAME VARCHAR
,   MIDDLE_NAME VARCHAR
,   LAST_NAME VARCHAR
,   PREFIX VARCHAR(50)   
)
;


CREATE TABLE IF NOT EXISTS ODS.ADDRESS 
(
    ADDRESS_ID INTEGER IDENTITY(1,1)
,   ADDR_1 VARCHAR
,   ADDR_2 VARCHAR
,   CITY VARCHAR
,   STATE VARCHAR
,   ZIPCODE VARCHAR(5)
)
;